#! /usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

'''
Sends a message to Slack with a formatted payload from a JSON file
generated by client.py
'''

import argparse
import json
import os
import sys

import requests

from datetime import date


def parse_args(cmdln_args):
    parser = argparse.ArgumentParser(
        description='Post formatted payload to Slack'
    )

    parser.add_argument(
        '--input',
        default='payload.json',
        help='Input (JSON)',
        required=False
    )

    return parser.parse_args(args=cmdln_args)

def post_to_slack(data):
    webhook_url = os.environ['SLACK_WEBHOOK']
    requests.post(webhook_url, json=data)

def build_payload_header() -> str:
    return [{
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": ":firefox-browser: iOS Performance Tests <{}>"
                        .format(date.today())
                    }
                }]

def build_payload_app_information():
    # Show commit and date
    return [
            {
            "type": "context",
            "elements": [
                {
                    "type": "plain_text",
                    "text": ":github: Commit: <{}>"
                    .format(os.environ['GIT_COMMIT']),
                }
            ]
        }
    ]

def build_payload_content(dataset: dict) -> list:
    # Print only 4 decimals
    for dictionary in dataset:
        for key, value in dictionary.items():
            if key != "testName":
                dictionary[key] = round(float(dictionary[key]),4)

    new_data = [{k: v for k, v in d.items() if v != 0.0} for d in dataset]
    first_string = new_data[1]
    slack_payload = []

    for dic in new_data:
        s = json.dumps(dic)
        string = s.replace("testName", "") 
        string2 = string.replace("\"", "")
        string3 = string2.replace("()", "*")
        string4 = string3.replace(":", "=")
        string5 = string4.replace("TabsPerformanceTest/", "*")
        string6 = string5.replace(",", "\n")

        each_test_data = {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": string6[2:-1]
                        }
                    ]
            }
        slack_payload.append(each_test_data)

    return slack_payload

def build_payload_footer():
    return [
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": ":testops-notify: created by [<{}|{}>]"
                            .format(
                                "https://mana.mozilla.org/wiki/x/P_zNBw",
                                "Mobile Test Engineering")
                            }
                        ]
                }
            ]

def build_payload_link_to_content():
    return [
                {
                "type": "actions",
                "elements": [
                    {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": ":mag: Check all trending data"
                    },
                    "value": "click_me_123",
                    "url": "https://docs.google.com/spreadsheets/d/1BqsYNhV1eQQR5e76VmolPsKwsXN7RbG58Slc4JeAE7k/edit#gid=0"
                }
            ]
        }
    ]

def main():
    args = parse_args(sys.argv[1:])
    
    try:
        with open(args.input) as data_file:
            dataset = json.load(data_file)
            header = build_payload_header()
            app_info = build_payload_app_information()
            content = build_payload_content(dataset)
            content_link = build_payload_link_to_content()
            footer = build_payload_footer()
            divider = [{"type": "divider"}]

        data = {'blocks': header + app_info + divider + content + divider + content_link + footer}
        post_to_slack(data)

    except FileNotFoundError as e:
        print(e)
        sys.exit(1)

if __name__ == '__main__':
    main()
